### PR TITLE
feat: support http cookies

### PR DESCRIPTION
**Pull request by nuomi1**
I found the latest tag is in the main branch, so I submitted the code to the main branch. If you need to adjust the merged branch, please feel free to do it directly.

### CODE REVIEW

**Comment by MaatheusGois** [comment]
@nuomi1  thanks so much for your contribution!

**Comment by MaatheusGois** [comment]
@nuomi1  we have a lot of conlficts coming :( Could you can recreate the PR from the develop?

**Review by MaatheusGois — CHANGES_REQUESTED** [review]
Change the base to develop

**Comment by nuomi1** [comment]
> Change the base to develop

Done.

**Review by MaatheusGois — APPROVED** [review]

**Pull request merged**
